---
# - name: Provisioning PostgreSQL Server 
#   hosts: db
#   become: yes
#   roles:
#     - postgres

# - name: Provsioning NFS server
#   hosts: nfs
#   become: yes
#   roles:
#     - nfs

- name: Provsioning Odoo server
  hosts: srv
  become: yes
  roles:
    - odoo

- name: Provisioning Proxy
  hosts: proxy
  become: yes
  roles:
    - proxy