---
- name: install dependencies from apt
  apt:
    name: '{{dependencies}}'
    update_cache: yes

- name: Install nodejs npm
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - nodejs
  - npm
  - node-less

- name: Install npm packages
  command:
    cmd: "npm install --global less less-plugin-clean-css"